### ISSUE TITLE
add set relation options

### ISSUE THREAD

**Issue by Diluka** [doug-martin/nestjs-query#1036]
**Is your feature request related to a problem? Please describe.**
replace of a new set of relation ids on a record

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

**Describe the solution you'd like**
```graphql
mutation{
setTagsToItem(id:"1",relationIds:[1,2,3]){id}
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by mwoelk** [comment]
When using typeorm you should be able to create a custom create/update DTO that includes a field with the same name as your relation and an array type of the relations DTO. You can then use the ˋcascade: trueˋ - option ([typeorm cascades](https://github.com/typeorm/typeorm/blob/master/docs/relations.md#cascades)) on the relation in your entity together with ˋ orphanedRowAction: "delete"ˋ ([typeorm orphaned row action](https://github.com/typeorm/typeorm/issues/6382)) on the inverse side of the relation if you want to remove items that aren’t in the set anymore. This way you can use the update-mutation of the parent DTO.

this will either create new items, remove old ones that aren’t in the new set, update existing items or assign existing items.

**Comment by ridyio** [comment]
@mwoelk I have tried this solution on many to many relations but TypeORM throws error on required field not being provided. But i did provide the id and that is supposed to be all it needs to set the relation. on mutation an object like this is sent:
```
{
  "name": "Foo",
  "categories": [{"id": "1"},{"id": "2"}],
}
```
This would throw an error from TypeORM on `name` field of `category` not being provided. It seems TypeORM tries to create records instead of setting the relation. As far as i remember when saving a record with bare TypeORM providing only id did worked. Tried a few different approaches as well but couldn't make one roundtrip on creation for set relation work if you have any suggestion on how you did made it work i would appreciate letting me know.
