### ISSUE TITLE
DeleteMany filter not working as expected

### ISSUE THREAD

**Issue by henry-huynh-3508** [doug-martin/nestjs-query#1511]
**Describe the bug**
deleteMany filters are not working consistently with the 'eq' operator, (or maybe not working with some other operator, I have no clues)

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**
My env uses TypeOrm with Postgres db btw.
For simplicity's sake, I will simplify my codes. I have 2 files user.dto.ts and user.entity.ts that look like this

```
@ObjectType('User')
@Relation('business', () => BusinessDTO, { disableRemove: true })

export class UserDTO {
  @FilterableField(() => String, {
    allowedComparisons: ['eq', 'neq', 'and', 'or'],
  })
  id!: string;
}
```
```
@Entity()
export class UserEntity extends BaseEntity {
  @Index()
  @PrimaryColumn()
  id: string;
}
```

**Expected behavior**
This query should delete 2 records. However, the return count is always 0 and nothing is deleted
```
mutation deleteMultiUsers {
  deleteManyUsers(
    input: {
      filter: {
        id: { eq: "1", or: {id: {eq: "2"}} }
      }
    }
  ) {
    deletedCount
  }
}
```

I tried this one and unexpectedly it works for some magical reasons???
```
mutation deleteMultiUsers {
  deleteManyUsers(
    input: {
      filter: {
        id: { eq: "1"} 
      }
    }
  ) {
    deletedCount
  }
}
```
deleteOneUser working as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/19938004/150244606-a2a4ca3a-e786-401a-8bec-cc1eb3f50445.png)

**Desktop (please complete the following information):**
 - Node Version 17.03
 - Nestjs-query Version 0.30.0

**Additional context**

**Comment by luca-nardelli** [comment]
Hey, I'm not sure that `id: { eq: "1", or: {id: {eq: "2"}} }` is the correct syntax for OR filters, AFAIK `and/or` can only be put at the top level of a filter object.

Also, your second attempt with `{id: {eq: "..."}, and: {id: {eq: "...."}}}` is also not correct because it basically makes an AND between two ids, leading to 0 results.

Can you try the following?

`{or: [{id: {eq: "id1"}}, {id: {eq: "id2"}}]}`

I'm not sure if this is the correct syntax because I'm from my mobile, but it should be close enough.

BTW, I would probably use the `in` operator here rather than making a bunch of OR filters

**Comment by henry-huynh-3508** [comment]
Already tried with or but still 0 deleteCount
![image](https://user-images.githubusercontent.com/19938004/150574600-237e988d-3932-4e96-94bc-a047fc373dc8.png)

About the in operator, there is no in operator available in the filter! Would be nice to have this operator tho.
![image](https://user-images.githubusercontent.com/19938004/150574518-ffe3c525-f384-419f-b9e0-62e1a1b063bc.png)

**Comment by luca-nardelli** [comment]
I think you got the `or` part wrong. Everything you place outside the `or` is AND-ed with the rest, so you are not doing an OR filter with your syntax.

This is how you should use it:

```
input: {
      filter: {
        or: [
          {id: {eq: "id1"}},
          {id: {eq: "id2"}},
          {id: {eq: "id3"}},
        ]
      }
    }
```

Regarding your absence of the `in` filter, that's because you have `allowedComparisons: ['eq', 'neq', 'and', 'or'],` for your `id` field. You should enable the `in` comparison there as well, otherwise it's expected that you are not able to use it.

**Comment by henry-huynh-3508** [comment]
Thanks for the clarification. I got it to work with delete many now, also it seems `allowedComparisons: ['eq', 'neq', 'and', 'or']` has no real effect whatsoever. I add 'in' but nothing changes on the deleteFilter. 
They seem kinda counter-intuitive for me. `{or: [{id: {eq: "id1"}}, {id: {eq: "id2"}}]}` should be equivalent to `id: { eq: "1", or: {id: {eq: "2"}} }` . Wouldn't it make it impossible to build complex queries where you need multiple nested conditions?
