### ISSUE TITLE
[Regression]: StaticConnection.createFromArray was removed

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#163]
Dear @doug-martin ,

i noticed, that the `StaticConnection.createFromArray()` method was removed in the last update. See this commit here:
https://github.com/doug-martin/nestjs-query/commit/13c7bd90dae9e5d6ffd33a8813b2cdfcc75ae131#diff-6286edfbb6983083734736506f449291L40

Is there any particular reason for this? Maybe we can add this method back in? Or is the "replacement" for this method the `createFromPromise()`?

All the best

**Comment by johannesschobel** [comment]
Ok, i already managed to adapt my code to the latest version. Just wanted to give feedback, that this MAY BE a breaking change for others as well!?

**Comment by doug-martin** [comment]
@johannesschobel sorry about that!

I removed that because it did not provide for a way to create a proper connection. With a [zero version](https://semver.org/#spec-item-4) the API is subject to change, I've tried to keep all breaking changes as a minor version and features/bug fixes will be a patch. 

In hindsight I should have created a migration doc :(

**Comment by johannesschobel** [comment]
Dear @doug-martin 
thanks a lot for your reply. Yeah, i know, that the `0.x` version is not stable and may be subject to a lot of changes. I just thought, this was a change by accident - so i reported it here.

Nevermind, i just changed my code accordingly to use the new / old `createFromPromise` and it works just fine ;) All good!

Thanks for your time
