### ISSUE TITLE
[Feature] Add support for aggregation queries

### ISSUE THREAD

**Issue by sebargarcia** [doug-martin/nestjs-query#345]
First of all congratulations on an excellent library! It´s made life much easier! 
It would be great if we could have aggregate queries like the Hasura GraphQL engine has. I mean aggregate operators like **count, sum, avg, max, min** 
For reference documentation please see https://hasura.io/docs/1.0/graphql/manual/queries/aggregation-queries.html

Sorry for my English and thank you for the amazing library.

**Comment by doug-martin** [comment]
@sebargarcia I just added aggregation support in `v0.17.0` 

Check out the docs [here](https://doug-martin.github.io/nestjs-query/docs/graphql/aggregations). Open another issue if you run into any issues! 

Thanks for the feature request!

**Comment by sebargarcia** [comment]
Wowww!!!! This is really cool! Thank you! 🍻🍻👏👏👏

**Comment by innomal** [comment]
@doug-martin Very useful update thanks, Just one question: It wasn't clear why a separate type was used for Aggregate filter when structure seems to be same as normal query filter.
```
type UserFilter {
and: [UserFilter!]
or: [UserFilter!]
id: IDFilterComparison
mobileNumber: NumberFieldComparison
lastName: StringFieldComparison
}
```

```
type UserAggregateFilter {
and: [UserAggregateFilter!]
or: [UserAggregateFilter!]
id: IDFilterComparison
mobileNumber: NumberFieldComparison
lastName: StringFieldComparison
}
```

The point is maybe same query parameter could be used for both when combined.

**Comment by sebargarcia** [comment]
I think there are not the same, if you see they returns different array types objects, the first one returns not aggregated data and the second one the aggregated data, so they have to be different schema types in graphql

**Comment by doug-martin** [comment]
@innomal in your example they are the same bout they could be different, the agggregation filter does not currently support querying by relations.

The other reason (and main reason) is that in the last couple of feature releases they have been breaking changes because I have had to split generated filters and types between the different operations. By splitting them I can add feature enhancements to the library for specific pieces of the resolver without potentially changing the generated schema in other endpoints.

**Comment by innomal** [comment]
@doug-martin I understand, Thanks for the explanation.
