### ISSUE TITLE
[Enhancement] Should return totalCount for calculating total pages

### ISSUE THREAD

**Issue by izundo-viennv** [doug-martin/nestjs-query#43]
@doug-martin  For now, I found that we just only paginate page by page, how can I do to paginate with total pages, because I don't know `totalCount` and for example If I have 100 pages, now I'm at page 2, how to jump to page 50

**Comment by doug-martin** [comment]
I left this off for now, because counts can be expensive, in postgres it can mean a full table scan. 

I'll look into this more after I work through the other issues.

**Comment by izundo-viennv** [comment]
@doug-martin the library should have an option for user to decide to use, it'll be unreasonable if when the user search something and they don't know how many results found, right?

**Comment by johannesschobel** [comment]
Dear @izundo-viennv ,
as you may noticed, this package uses the `relay-pagination` style, which is a `cursor-based` pagination. This, in turn, means, **that you cannot properly calculate the amount of pages**! 

When using a `page-based` pagination style, the request contains the page-number to be returned and the amount of entries per page. In this context, you can calculate the total amount of pages (i.e, you want to have 10 items, you are currently on page 2, and there are a total amount of 100 items). Therefore, there must be 10 pages in total.

However, in the `cursor-based` pagination style, you cannot do this easily, because you request 10 items, **after** a specific cursor. Note, that this cursor **must not** be the cursor at the end of one page. For example, you can get the cursor to the 74th item (from 100) and then request the next 10. You would still have (technically) 10 pages (100 items / 10 items per page), but the meaning of these 10 pages are totally "off". Because you would now be on page 7.4 (which makes totally no sense at all).

Note that these are two totally different pagination styles, each one having different use-cases. I think, the `cursor-based` pagination style as used in this package is the more versatile approach. Finally, the `relay-style` is awesome as hell ;) Please note that the official relay style document proposed by facebook (!) does not have a `totalCount` either: https://facebook.github.io/relay/graphql/connections.htm 

All the best

**Comment by johannesschobel** [comment]
to further explain the quote
> "because counts can be expensive"

This often means, that you have to make an additional (!) sql statement to query the count. Especially in the context of "nested relationships" this may result in `n*2` queries instead of `n`.. Further, those "count queries" (lets call them so for now) are not cacheable by the database and you cannot "optimize" them with index or stuff like this.. they dramatically decrease the overall performance!

**Comment by doug-martin** [comment]
@johannesschobel thank you for the great response. You clearly explained all of my hesitations in making this change very well kudos!

**Comment by Diluka** [comment]
@doug-martin Is there any plan about `offset` and `totalCount` in pagination?

**Comment by doug-martin** [comment]
@Diluka I'm currently working on a feature that will allow you to specify the paging strategy, either `cursor` or `limitOffset`. 

When using `cursor` (the default value) everything will operate the same way it does today with connections.  If you set it to `limitOffset` your queries and relations will return an array and when paging you will be able to use `limit` and `offset`.

I will probably eventually add `totalCount` I just need to get through the current backlog of issues, and figure out a good way to handle this.

**Comment by Diluka** [comment]
@doug-martin no matter the strategy is. it needs to be connection too. now I am using this lib https://www.npmjs.com/package/nest-graphql-utils  to do both cursor-based and page-based pagination

**Comment by doug-martin** [comment]
@izundo-viennv I've added the ability to enable `totalCount` on cursor based connections in `v0.15.0`!

Docs:
* https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#paging-with-total-count
* https://doug-martin.github.io/nestjs-query/docs/graphql/relations#total-count

**Comment by Diluka** [comment]
@doug-martin actually, you need add `totalCount` to page based connections.

we use `offset`, `limit` and `totalCount` to calculate pagination toolbar's page index buttons.

but cursor based connections only previous and next buttons, `totalCount` is useless for it.

**Comment by doug-martin** [comment]
@Diluka you are adding on to a previous issue without context. I have seen two comments that appear to be slightly contradictory

```
no matter the strategy is. it needs to be connection too. now I am using this lib https://www.npmjs.com/package/nest-graphql-utils to do both cursor-based and page-based pagination
```

and 

```
you need add totalCount to page based connections.

we use offset, limit and totalCount to calculate pagination toolbar's page index buttons.

but cursor based connections only previous and next buttons, totalCount is useless for it.
```

Looking into the first comment the `offset` parameter does not apply to the connection spec https://relay.dev/graphql/connections.htm, the `offset` parameter seems to be a shortcut to bypass connections. 

With that said I'm not completely opposed to adding offset, however I would like to understand the use case better to prevent wasted effort. Cursor based connection are intended for infinite paging. I think I understand your request but without a concrete example I do not want to add/change the connection definitions. 

Please create a new issue with the use case and examples of what you would expect the functionality to be. From there we can continue the discussion.

**Comment by Diluka** [comment]
connection is compatible with both cursor and page based pagination.
https://graphql.org/learn/pagination

**Comment by heavenkiller2018** [comment]
why  does 'Paging with Total Count '   ONLY applly to CURSOR connections?

we use offset, limit and totalCount to calculate pagination toolbar's page index buttons.

but cursor based connections only previous and next buttons, totalCount is useless for it.

**Comment by johannesschobel** [comment]
@heavenkiller2018 no, it is not `useless`. Consider, for example, the use-case that you would like to write "id 1 - 10 from 54" above the table. Therefore, you would need the `totalCount` to get this information
