### ISSUE TITLE
[Issue]: AssemblerService takes Objects Input instead of Entities

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#51]
Dear @doug-martin ,

the newly added `AssemblerService` (added in `v 0.6.0`) takes an `xDTO` instead an `xEntity`.
Should this be changed to `Entities`?

https://github.com/doug-martin/nestjs-query/blob/81a1cd59e13f6d91c26df1e70d9b0f047e1f6ecc/packages/core/src/services/assembler-query.service.ts#L19-L22

All the best,
Johannes

**Comment by doug-martin** [comment]
This is intentional. The assembler query service only works on DTOS, bouncing back and forth between entity and DTO depending on which method is being used would be confusing. 

Say for example you have a DTO

```ts
class TestDTO {
   foo: string;
   bar: string:
}
```

and an entity 
```
class TestEntity {
   fooString: string;
   barString: string;
}
```

If the `AssemblerQueryService` accepted a partial of entity for creates and returned a DTO it could lead to confusion pretty quickly.

**Comment by johannesschobel** [comment]
Ah, ok. Didn't get that ;) thanks for the clarification
