### ISSUE TITLE
[Question]: How to properly use the AssemblerService

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#52]
Dear @doug-martin ,

how can i properly use the `Assembler` within the `Resolver`?
For example, in #41 we have excessively discussed that the `Service` should work on `Entities` and not on `Objects`. Your newly published `v 0.6.0` version already introduced these changes :+1: 

However, i would like to use the `AssemblerService` within the `Resolver`.

My use-case looks like this:
1) add a custom `@Mutation` or `@Query` method in my resolver
2) this method uses a custom method in the underlying service. This method, in turn, works on the `Entities` and not on `DTOs`. That was the reason to introduce the changes described in #41 .
3) The result of this method may be a changed `Entity` or whatever
4) The latter has to be transformed to a `DTO` (`ObjectType`) in order to be returned via the GQL endpoint.

However, with the newly introduced `AssemblerService` that **wraps** the `QueryService`, it is not possible to achieve the latter.

The `QueryService` and `AssemblerService` as **still** coupled together, because the `AssemblerService` internally uses the `QueryService`. Wouldn't it be better to have a dedicated `AssemblerModule` that handles the transformation? Because this way it would be easy to "plug in" the `Assembler` where they are needed.

I would really like to see something like this (be aware, this is quite ugly dummy code, haha):
```ts
// user.module.ts
@Module({
  imports: [TypeOrmModule.forFeature([UserEntity]), AssemblerModule],
  providers: [UserResolver, UserService],
})
export class UserModule {}

// user.resolver.ts
@Resolver(of => UserObject)
export class UserResolver extends CRUDResolver(UserObject, {
  create: { ... },
  // ... custom configuration here
}) {
  constructor(
    readonly service: UserService,
    readonly assemblerService: DefaultAssembler<UserObject, UserEntity>, // or a dedicated UserAssembler if the transformation is complex!
  ) {
    super(service);
  }

  @Mutation(returns => UserObject, {...} )
  async doFancyStuff(@Args('input') input: ... ): Promise<UserObject> {
    const entity = await this.service.findById(id);
    const a = await this.service.customMethod(entitiy); // this returns a UserEntity
    return await this.assemblerService.convertToDto(a);
  }
}
```

What do you think?

All the best,
Johannes

**Comment by johannesschobel** [comment]
I am very sorry, if i may be misinterpreting the usage of the `assembler` for now :laughing: please correct me, if i understood it wrong

**Comment by doug-martin** [comment]
I'm not sure I completely understand, but I'll take a stab.

I would do this in my service, and not the resolver.

For example

```ts
@QueryService(UserObject)
export class UserAssemblerService extends AssemblerQueryService<UserObject, UserEntity> {
  constructor(
    readonly assembler: UserAssembler,
    // This could also be a custom query service if you have your own.
     @InjectTypeOrmQueryService(UserEntity) queryService: QueryService<UserEntity>,
  ) {
    super(assembler, queryService);
  }
  
  async doFancyStuff(id: string): Promise<UserObject> {
    const entity = await this.queryService.findById(id);
    const a = await this.queryService.customMethod(entity); // this returns a UserEntity
    return this.assembler.convertToDTO(a);
  }
}
```

```ts
@Resolver(of => UserObject)
export class UserResolver extends CRUDResolver(UserObject, {
  create: { ... },
  // ... custom configuration here
}) {
  constructor(
    readonly service: UserAssemblerService,
  ) {
    super(service);
  }

  @Mutation(returns => UserObject, {...} )
  async doFancyStuff(@Args('input') input: ... ): Promise<UserObject> {
    return this.service.doFancyStuff(input.id);
  }
}
```

I am not sure what an AssemblerModule would accomplish in this scenario, it would still need to know what the underlying QueryService and DTO type is to translate back and forth. 

If we put it in the resolver, in other places where we need the translation the logic would need to be duplicated or inject the resolver. My thoughts on having a two services means you can choose if you need an assembler or not in either the resolver or other services. Another benefit I see from the AssemblerQueryService is its single responsibility of translating back and forth. 

I hope this makes sense. 

Thanks again for the detailed write up we'll get this worked out :)

**Comment by johannesschobel** [comment]
Dear @doug-martin ,

thanks a lot for your answer and your dummy-code. I was thinking about something similar my own, but was not sure if this would be the way to go. I thought about "transforming forth and back" in the `Resolver` as it would be more meaningful for me.
I.e., the resolver takes the query from the user, transforms it properly, calls the underlying services (i.e., get data from the database) and then transforms it back to an output structure.

I am not quite sure if i fully agree with the "wrapping" part of the regular `TypeOrmQueryService` and the `AssemblerQueryService`.

In your code example above, the service that is injected into the `Resolver` (i.e,. the `UserAssemblerResolver`) still does not return `Entities`, but it returns (again) `Objects`. I know, that this is because of the fact that the service internally transforms the data. However, this still creates the "soft-dependency" between the entities and objects.

Say, for example, i would need this `doFancyStuff()` method in several places, or the `Entity` result from `doFancyStuff()` should be used in other methods as well, i would need to inject **both** the regular `TypeOrmQueryService` and the `AssemblerService` in the `Resolver`, right? Or i would need to wrap all those methods in the `AssemblerService` and, therefore, kind of duplicating the latter.

Am i completely on a wrong track?

All the best and thank you very much for discussing this issue!

**Comment by doug-martin** [comment]
I'd like to preface my response with this is my personal opinion, and I think the building blocks are here to do it either way.

With that said I've seen this done a couple of different ways, but in your case since its outside the scope of the CRUD stuff, I would extend `TypeOrmQueryService` with the business logic of working with the entities (this encapsulates the logic of how your database is wired together) from the resolver and keeps it in one place.  

The assembler currently acts as the translator for the resolver but it could be used by your controllers (their just classes right?), so its only responsibility is to transform the entities to DTOs. 

In places where you dont need the DTO (if i recall correctly from your other issues that would be in your rest services?) I would use the custom typeorm service directly.

Assigning the single responsibilty to each service does the following
* Prevents duplication of logic, the typeorm service handles interacting with the persistence layer. 
* Makes the code testable.
  * You can test that the typeorm service makes the right db calls
  * Assembler service tests just the transform and the correct typeorm service call.  
  * Resolver make sure you call the right service method
* Resusable by both the controllers (or other services) and your resolver.
* Makes your code more maintainable:
   * If later on you dont need the assembler, great! replace the service you inject into your resolver.
   * You have to interact with other tables in the typeorm service, awesome! update the logic there and everything else stays the same. 
   * You decide to switch from a Typeorm to Sequelize (I've almost got this working), again you can just swap out the typeorm query service with the new one and your assembler and resolver stay the same.  

This does come at a cost however, you have additional services, if the service is going to be long lived it may be worth it, if not I would combine the entity and DTO and skip the assembler all together. 

I separate them in the docs to be clear on what is needed by the resolver vs the typeorm service but if your entity and DTO are copies of eachother you can combine them.

One of the reasons I seperated the layers out like I did was to allow for adding other transports later on, this is currently a graphql library but as I hinted at above there could also be a rest implementation (or RPC who knows) and I didnt want to have to duplicate the logic between the two transport types. The suggestion you made of making the TypeOrmQueryService to only work in entities is already paying off with implementing a sequelize query service. 

I have a question, do the docs feel like they are pushing you down a certain path, or that a DTO is required?

**Comment by doug-martin** [comment]
As a followup to my response an example would be

```ts
@QueryService(UserEntity)
export class UserDatabaseService extends TypeOrmQueryService<UserEntity> {
  constructor(
     @InjectRepository(UserEntity) repo: Repository<UserEntity>,
  ) {
    super(repo);
  }
  
  async doFancyStuff(id: string): Promise<UserObject> {
    const entity = await this.findById(id);
    return this.customMethod(entity); // this returns a UserEntity
  }

 customMethod(user: UserEntity): Promise<UserEntity> {
     // do some custom business logic.
  }
}
```

```ts
@QueryService(UserObject)
export class UserAssemblerService extends AssemblerQueryService<UserObject, UserEntity> {
  constructor(
    readonly assembler: UserAssembler,
    // This could also be a custom query service if you have your own.
     userDbService: UserDatabaseService,
  ) {
    super(assembler, userDbService);
  }
  
  async doFancyStuff(id: string): Promise<UserObject> {
    const entity = await this.userDbService.doFancyStuff(id);
    return this.assembler.convertToDTO(entity);
  }
}
```

```ts
@Resolver(of => UserObject)
export class UserResolver extends CRUDResolver(UserObject, {
  create: { ... },
  // ... custom configuration here
}) {
  constructor(
    readonly service: UserAssemblerService,
  ) {
    super(service);
  }

  @Mutation(returns => UserObject, {...} )
  async doFancyStuff(@Args('input') input: ... ): Promise<UserObject> {
    return this.service.doFancyStuff(input.id);
  }
}
```

**Comment by johannesschobel** [comment]
Dear @doug-martin ,

wow, thank you SO much for your very detailed answers and the passion you put into this project :+1: I really (!) appreciate it!

I think I got your thought-process on this one now..
The main issue I had, was that i did it the other way round in another project. In this project we had a `http REST` and `GraphQL` interface for the clients (again, haha). Main application structure was as follows:

### REST
`Request` was sent to the application and routed to proper method in a `Controller`. The controller gets the `Body` of the `Request` injected and then transforms specific fields to a neutral `DTO`. This DTO, in turn, was not related to REST or GraphQL, it was just a plain interface. The `DTO` was then passed to completely "neutral" `Services`, that interact with the DB. The Service, in turn, would then return an `Entity` (or a list of entities). The latter were transformed to `Response` objects and returned back to the client.

### GraphQL
`Request` was sent to the application and routed to proper method in a `Resolver`. The resolver gets the `InputType` and then transforms specific fields to a neutral `DTO` (see above). The `DTO` was then passed to completely "neutral" `Services` (the same as above), that interact with the DB. The Service, in turn, would then return an `Entity` (or a list of entities). The latter were transformed to `ObjectType`s and returned back to the client.

In this approach, the only thing that really changed was the mapping in the `Controller` or `Resolver` classes. Everything "beneath" this surface was completely untouched.

And i think, this got me stuck with my thoughts "why doesn't he transform the data in the resolver but in the service"..

Thank you very much for your time and help

**Comment by doug-martin** [comment]
I added more docs to the assemblers section and moved to an advanced section. @johannesschobel if you find areas that could be expanded or clarified **please** feel free to modify and issue a PR!

https://doug-martin.github.io/nestjs-query/docs/concepts/assemblers#why
