### ISSUE TITLE
[Question]: Support SoftDeleting

### ISSUE THREAD

**Issue by johannesschobel** [doug-martin/nestjs-query#54]
Dear @doug-martin ,

yesterday evening i stumbled upon **this** awesome PR in the `typeORM` repository: https://github.com/typeorm/typeorm/pull/5034

This PR, basically, adds the whole `soft delete` stuff to the `Repository` classes and so on. Best thing is, it has already been merged and is ready to be used. The docs of the project, however, does not mention it (yet).

So here is my question:
Shall we add support for `softDeleting` entities in this package as well?
I was thinking about something like this:
```ts
// user.resolver.ts
@Resolver(of => UserObject)
export class UserResolver extends CRUDResolver(UserObject, {
  // ...
  delete: { ..., softDelete: true },
  read: { ..., includeSoftDeleted: true }
}) {
  constructor(readonly service: UserService) {
    super(service);
  }
}
```

For the `delete` prop, we could add a new property `softDelete: boolean` to all levels (i.e.,`delete`, `delete.one` and `delete.many`). Then we add some new methods to the `QueryService` interface and the `TypeOrmQueryService` respectively, to implement the following methods
```ts
export interface QueryService<DTO> {
  // ... already defined methods
  /**
   * SoftDelete a single record by id.
   * @param id - the id of the record to softDelete.
   */
  softDeleteOne(id: number | string): Promise<DTO>;

  /**
   * SoftDelete multiple records using a filter.
   *
   * @param filter - the filter to find records to softDelete.
   */
  softDeleteMany(filter: Filter<DTO>): Promise<DeleteManyResponse>;

  /**
   * Restore a single record by id.
   * @param id - the id of the record to be restored.
   */
  restoreOne(id: number | string): Promise<DTO>;

  /**
   * Restore multiple records using a filter.
   *
   * @param filter - the filter to find records to be restored.
   */
  restoreMany(filter: Filter<DTO>): Promise<UpdateManyResponse>; // i assume that it will be a UpdateManyResponse ;)
}
```

And in the respective service use the `this.repo.softRemove()` method instead the `this.repo.remove()`.

Note that all `find()` and `query()` methods should respect the `softDeleted` entities by default. I.e., they are **not** present in the resultset anymore. If there should be additional routes to output the soft-deleted ones (i.e., **only** the softdeleted ones or all (non-deleted and soft-deleted)), additional `find(...)` methods should also be added.

Finally, the soft-delete stuff **also** works on relationships, which is soooooooooooooo awesome. The author of this PR added an additional `cascade` option to the `@XToY()` decorators to `soft-delete` over relationships.

What do you think about this feature?
All the best,
Johannes

**Comment by doug-martin** [comment]
@johannesschobel from what I have seen this is a common enough feature to support!

What haven't researched enough yet, to have an opinion on, is if it should be in the resolver or at the query service. If you put it at the resolver it then has control over whether or not a soft delete occurs at the request level, at the query service you could reuse it in multiple resolvers without having to worry if `softDelete` was specified or not. 

If you want to work on this go ahead, just reply back to this PR, otherwise I'll look into it once I'm done with the sequelize support.

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
my suggestion would be as follows:
* create several new methods on the `DatabaseService` level (i.e., to soft-delete an entity, to hard-delete an entity, to restore an entity, ...) so the service would be greatly enhanced with these new features.
* add those methods to the `AssemblerService` as well

Now those features can be used independently..
Finally, i would
* add new options to the `Resolvers` to indicate, if soft-delete should be enabled or not. This will be new options for the `delete` options. If, for example `delete.softDelete = true` is set, the `deleteOne` and `deleteMany` simply calls other methods "under the hood".

What do you think about this approach?

**Comment by doug-martin** [comment]
@johannesschobel I finally got around to integrating this!

I deviated from you suggestion a little bit opting to keep this at the service level. I decided to do this because.

1. When adding the `@DeleteDateColumn` decorator typeorm automatically changes the way reads work to always add a filter to remove records where the columns is not null.
2. Other ORMs store this info at the entity level.

Those two details made it where deciding at the resolver whether or not soft deletes are enabled not feasible.

I left the implementation lite for now and we can enhance once more use cases come in. I did include examples of how to add `restore` mutations to the resolver. I couldnt not find a way to force reading deleted records, but the docs around this feature are really sparse at the moment, so the may be a way I just am unaware of it. 

Thanks again for the great write up!

**Comment by johannesschobel** [comment]
Dear @doug-martin ,

sorry I come back to this issue. I carefully read your documentation on the `TypeOrm SoftDelete` feature and studied your example.

Thereby, I thought, that it may be possible to add a `restore` parameter to the `CRUDResolver`? It seems that you would re-write the same mutation over and over again to restore one or multiple entities.

The resolver would just call the `service.restore(id)` method. The latter, however, has to be implemented in respective service implementations (i.e., for `TypeORM` or `Sequelize`). Worst case could be, that a respective ORM does not support `SoftDeletes`, so a default implementation of the `restore()` method would just do nothing.

What do you think?

All the best,
Johannes

**Comment by johannesschobel** [comment]
> I couldnt not find a way to force reading deleted records, but the docs around this feature are really sparse at the moment, so the may be a way I just am unaware of it.

I will take a look at it this week, as i would like to integrate `SoftDeletes` in my API

**Comment by doug-martin** [comment]
@johannesschobel would you mind creating a new issue to track this?
