### ISSUE TITLE
Date comparison not working properly

### ISSUE THREAD

**Issue by a777med** [doug-martin/nestjs-query#920]
**Describe the bug**
Query filters return wrong data when using the `eq` and `gt` filters with `GraphQLISODateTime` fileds.

**To Reproduce**
1. Make a filed with the type GraphQLISODateTime.
2. Filter on the field with eq or gt.
3. Use this query as an example

> {
  products(filter: { updatedAt: { gt: "2021-03-01T11:19:11.862Z" } }) {
    nodes {
      id
      name
      price
      isActive
      createdAt
      updatedAt
    }
  }
}

**Expected behavior**

> {
  "data": {
    "products": {
      "nodes": []
    }
  }
}

**Current behavior**
> {
  "data": {
    "products": {
      "nodes": [
        {
          "id": "f0d32a48-0c58-4bf8-8020-b1fab5b58a30",
          "name": "Edited Product 2",
          "price": 7,
          "isActive": true,
          "createdAt": "2021-03-01T11:19:11.862Z",
          "updatedAt": "2021-03-01T11:19:11.862Z"
        }
      ]
    }
  }
}

Notice how the `updatedAt` of the node that got returned is exactly equal to the date in `gt`.

**Desktop:**
 - Node v14.15.5
 - Nestjs-query v0.23.1
 - typeorm v0.2.31
 - @nestjs/typeorm v7.15

**Additional context**
When using the exact same query as above but with `eq` instead of `gt`, an empty nodes list is returned.
I am using TypeORM

**Comment by doug-martin** [comment]
@a777med I've tried this locally, and from my testing it is working as expected, I suspect in this case your `updatedAt` column in the database is using a higher precision (most likely microseconds) so instead of your `updatedAt` being `2021-03-01TT11:19:11.862Z` its probably something more like `2021-03-01TT11:19:11.862362Z` which is greater than `2021-03-01TT11:19:11.862000Z`. 

If you really want a lower precision you could do something like the following in your entity

```ts
@CreateDateColumn({ precision: 3 })
createdAt!: Date;

@UpdateDateColumn({ precision: 3 })
updatedAt!: Date;
```

Thanks for submitting an issue!
